version: '3.7'
services:
  python:
    build:
      context: .
      dockerfile: DockerfileDev    
    volumes:
      - '.:/app'
    ports:
      - '8080:8080'
      - '8000:8000'
    stdin_open: true
    tty: true